### ISSUE TITLE
Can I fund this project

### ISSUE THREAD

**Issue by sacru2red** [neostandard/neostandard#51] opened 2024-06-10 00:01 UTC
I'm not a native English speaker so I don't know exactly what it's called.
Can I fund this project?

I want to help, but I don't have the time or ability.

like [opencollective](https://opencollective.com/)

**Comment by bcomnes** [comment] 2024-06-10 17:59
Soon. Subscribe to https://github.com/neostandard/neostandard/issues/21 and watch for future announcements. Thank you for your support!

**Comment by bcomnes** [comment] 2024-06-10 18:01
Duplicate of https://github.com/neostandard/neostandard/issues/21

**Closed by bcomnes** 2024-06-10 18:01 UTC
